# Use the official Node.js 22 image as the base image
FROM node:22

# Set the working directory inside the container to /usr/src/app
# All following commands will be executed relative to this directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (or yarn.lock) into the container
# This helps leverage Docker layer caching to avoid reinstalling node_modules unless they change
COPY package*.json ./

# Install app dependencies defined in package.json
RUN npm install

# Copy the rest of the application code into the container
COPY . .

# Compile TypeScript code
RUN npm run build

# Expose port 3000 so it can be accessed from outside the container
EXPOSE 3000

# Define the command to run the application when the container starts
CMD ["npm", "start"]